replicaCount: 1

image:
  repository: "registry.hub.docker.com/pawbis/twitter_vis:1.0"
  pullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes:
  - name: volume-1
    hostPath:
      path: /twitter_api_folder

volumeMounts:
  - name: volume-1
    mountPath: /twitter_api_folder

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8888