//It is template for potential CI pipeline in order to build/test code, since mine was written to be containerized.
//As the code has to be tested before containerized mine wont be usefull.
//CI part of the file
pipeline {
    agent any
    stages {
        stage("Cleaning up!"){
            steps{
                deleteDir()
            }
        }
        stage("Cloning repository!"){
            steps{
                sh "git clone https://github.com/pawbis/Twitter_sentiment_analysis.git" //cloning repository
            }
        }
        stage("Build"){
            steps{
                sh "echo test" 
                }
            }
        
        stage("Test"){
            steps{
                sh "echo test"
            }
        }
        //deploy part of the jenkinsfile
        stage("vis container") {
            agent{
                docker{
                    image 'pawbis/twitter_vis:1.0'
                    registryUrl 'https://registry.hub.docker.com'
                    reuseNode true
                }
            }
            steps{
                sh 'echo if you see this it is working'
            }
        }
        stage("api container"){
            agent{
                docker{
                    image 'pawbis/twitter_api:2.0'
                    registryUrl 'https://registry.hub.docker.com'
                    reuseNode true
                    args '--restart=always'
                }
            }
            steps{
                sh 'echo if you see this it is working'
            }
        }
    }
}