apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twitter-analysis.fullname" . }}
  labels:
    {{- include "twitter-analysis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "twitter-analysis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "twitter-analysis.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12}}