apiVersion: v1
kind: Service
metadata:
  name: {{ include "twitter_vis.fullname" . }}
  labels:
    {{- include "twitter_vis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "twitter_vis.selectorLabels" . | nindent 4 }}
